In [7]:
import numpy as np

In [8]:
def relu(x):
    return np.maximum(0, x)

In [9]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [10]:
def softmax(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

In [17]:
#輸入層的參數
x = np.array([4.0 , 3.0 , 5.0 , 2.0 , 6.0 , 7.0])
x.shape

(6,)

In [48]:
#第一隱藏層：五個神經元

In [24]:
#第一隱藏層的權重
w1 = np.array([[2.5,3.0,1.5,6.5,4.0],
               [2.0,4.0,2.5,6.0,4.5],
               [1.5,3.5,3.0,6.5,4.0],
               [2.0,3.5,1.0,6.0,3.0],
               [2.5,4.5,1.5,4.0,2.5],
               [1.5,2.5,5.5,2.0,2.0]])
w1.shape

(6, 5)

In [31]:
#偏置
b1 = np.array([3.0,3.5,2.0,5.5,3.0])
b1.shape

(5,)

In [101]:
#第一隱藏層輸出(未經過激發函數)
z1 = np.dot(x,w1)+b1
print(z1)
print(z1.shape)

[ 56.   96.5  80.  132.   87.5]
(5,)


In [100]:
#使用激發函數
h1 = relu(z1)
print(h1)
print(h1.shape)

[ 56.   96.5  80.  132.   87.5]
(5,)


In [54]:
#第二隱藏層：四個神經元

In [59]:
#第二隱藏層的權重
w2 = np.array([[2.5,1.5,1.5,-2.5],
               [-1.5,1.0,3.5,3.0],
               [-2.5,-2.0,4.0,-4.5],
               [3.5,3.5,-2.0,1.0],
               [-5.5,5.5,2.5,-2.5]])
w2.shape

(5, 4)

In [60]:
#偏置
b2 = np.array([3.5,2.0,5.5,2.0])
b2.shape

(4,)

In [98]:
#第二隱藏層輸出(未經過激發函數)
z2 = np.dot(h1,w2)+b2
print(z2)
print(z2.shape)

[-220.5   965.75  702.   -295.25]
(4,)


In [97]:
#使用激發函數
h2 = relu(z2)
print(h2)
print(h2.shape)

[  0.   965.75 702.     0.  ]
(4,)


In [66]:
#第三隱藏層：四個神經元

In [74]:
#第三隱藏層的權重
w3 = np.array([[0.5,1.5,0.5,0.5],
               [0.5,1.0,1.5,2.0],
               [1.5,1.0,2.0,0.5],
               [0.5,2.5,1.5,0.5]])
w3.shape

(4, 4)

In [75]:
#偏置
b3 = np.array([1.5,3.0,2.5,4.0])
b3.shape

(4,)

In [96]:
#第三隱藏層輸出(未經過激發函數)
z3 = np.dot(h2,w3)+b3
print(z3)
print(z3.shape)

[1537.375 1670.75  2855.125 2286.5  ]
(4,)


In [95]:
#使用激發函數
h3 = sigmoid(z3)
print(h3)
print(h3.shape)

[1. 1. 1. 1.]
(4,)


In [87]:
#輸出層：三個神經元

In [88]:
#輸出層的權重
w_out = np.array([[0.5,1.0,1.5],
                  [1.5,1.0,0.5],
                  [2.0,1.5,0.5],
                  [1.0,0.5,1.5]])
w_out.shape

(4, 3)

In [89]:
#偏置
b_out = np.array([1.0,2.0,1.5])
b_out.shape

(3,)

In [94]:
#輸出層輸出(未經過激發函數)
z_out = np.dot(h3,w_out)+b_out
print(z_out)
print(z_out.shape)

[6.  6.  5.5]
(3,)


In [93]:
#使用激發函數
y_hat = softmax(z_out)
print(y_hat)
print(y_hat.shape)

[0.38365173 0.38365173 0.23269654]
(3,)
